### ISSUE TITLE
Drag and Drop between PC and NPC

### ISSUE THREAD

**Issue by Ikabodo** [David-Zvekic/DragTransfer#1]
Great work with this module, it was exactly what I was looking for.

Would it be possible to enable drag and drop between npcs and pcs in 5e, or would that cause issues? Right now they are different types, making the use of LootSheet5e module blocked. Or alternatively enable a "flag" on a specific actor overriding the drag and drop block.

As you said in your future features, you might create a player sheet with only an inventory, and that would of course solve this too even if the sheet won't look like the sheet you use personally, the main functionality will be there.

**Comment by David-Zvekic** [comment]
I'll investigate lootsheet.  I have no interest in re-inventing the wheel.
 maybe I can just make it compatible with lootsheet.

**Comment by McShaker** [comment]
Agreed.  Trying to find this exact functionality.  
If you can make compatible with lootsheet that would be awesome.

**Comment by David-Zvekic** [comment]
as of 1.1.0 you can use the Compatible Actor Type settings to now allow the module to work on npc<=> character transfers.

set the value to : 
"character":"npc"

It only works if the source is a linked actor (i.e. an actor opened directly form the actor sidebar, or using a linked token, because Foundry doesn't create an event for dropping inventory off an unlinked actor.  However this addresses this issue.  

Please tell me if you have any comments or input on the feature now.

Thanks!
