### ISSUE TITLE
Add support for Pathfinder 2 system

### ISSUE THREAD

**Issue by r-valyar** [David-Zvekic/DragTransfer#12]
It would be great to add support for PF2 system. I found that module **may** work under some circumstances I failed to nail down. 

In general the error below is displayed when I try to move item between PCs in the same or different category in the inventory. 
Also when move was working for some reason, when I try to move less than the total quantity, items disappear completely from the inventory.

![image](https://user-images.githubusercontent.com/63558984/151698001-8a7090c6-9f5f-443e-863f-8a3d598d26ee.png)

**Comment by David-Zvekic** [comment]
"when I try to move less than the total quantity"

it seems like the core of PF2 already knows something about drag and drop because otherwise how could it be prompting you regarding quantity?  Are you sure it doesn't already have the feature of this module built in?

DragTransfer has no notion of quantity. It literally assumes whatever is being dragged will be duplicated at the destination, so must be deleted from the source.

**Comment by r-valyar** [comment]
It seems you are right... there is already implementation of this feature and items can be moved between characters. I guess I assumed such thing does not exist because... it does not exist in many other systems by default. :)
